table SalesReturns
	lineageTag: 06eb3a0c-b148-4f0d-8f53-806492c38ceb

	column ReturnKey
		dataType: int64
		formatString: 0
		lineageTag: 6f32b9bd-0bfb-4540-8d55-7f5b13c28f76
		summarizeBy: count
		sourceColumn: ReturnKey

		annotation SummarizationSetBy = Automatic

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc4afa16-3f39-4e6e-996b-88823176df80
		summarizeBy: none
		sourceColumn: ReturnDate

		variation Variation
			isDefault
			relationship: c6de80fe-5f22-4d98-b1ef-b4d0f012a379
			defaultHierarchy: LocalDateTable_3c87e54c-318c-4460-998b-5ee330537f4a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7df180e-d414-449a-aa62-662ec5287b83
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SalesOrderNumber
		dataType: string
		lineageTag: 383bcdc3-f9e6-4839-a75c-6538f3c58039
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: f4b8af38-b28e-4434-b499-a3dacc6b8a9b
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: b7a036f0-ba41-4315-a853-1fe33b8b0d67
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: a5dcbc42-750c-4e9d-a398-e430635f8b8d
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: bd7a6690-0523-419d-bf13-2405483315d6
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReturnAmount
		dataType: double
		lineageTag: 893d5dd3-c2af-4f57-a3f7-a4c32e07e57e
		summarizeBy: sum
		sourceColumn: ReturnAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SalesReturns = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\elmnshawy\Desktop\DataX\Project one\SalesReturns.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnKey", Int64.Type}, {"ReturnDate", type date}, {"OrderDate", type date}, {"SalesOrderNumber", type text}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}, {"UnitPrice", type number}, {"ReturnAmount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

