table Customers
	lineageTag: 88917925-57ac-45fc-9c4f-4454c247c5bf

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 1be1a17d-d9ef-4bd3-8a03-19f86693c8ef
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 2076005f-c346-4dcb-b7eb-c95b69a78bd5
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column BusinessType
		dataType: string
		lineageTag: 2de0674c-a980-4ac3-84d0-2649b3c5c557
		summarizeBy: none
		sourceColumn: BusinessType

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 2645206c-b2c9-4e4c-950f-a0b98dfb0cd7
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column NumberEmployees
		dataType: int64
		formatString: 0
		lineageTag: c5b6f90d-b228-4cbd-8cfb-4f45a4d2d0e3
		summarizeBy: sum
		sourceColumn: NumberEmployees

		annotation SummarizationSetBy = Automatic

	column AnnualRevenue
		dataType: int64
		formatString: 0
		lineageTag: 53b1d80a-dda3-4e06-b71d-145e5a3dc886
		summarizeBy: sum
		sourceColumn: AnnualRevenue

		annotation SummarizationSetBy = Automatic

	column YearOpened
		dataType: int64
		formatString: 0
		lineageTag: 189dba97-31cb-487c-8b1a-608e6f690cae
		summarizeBy: sum
		sourceColumn: YearOpened

		annotation SummarizationSetBy = Automatic

	column CityName
		dataType: string
		lineageTag: b75bbd3b-bf55-48da-98e4-7c78847c3b6c
		summarizeBy: none
		sourceColumn: CityName

		annotation SummarizationSetBy = Automatic

	column StateCode
		dataType: string
		lineageTag: 33cbdfe1-94af-4581-ab30-01cb12ec0dec
		summarizeBy: none
		sourceColumn: StateCode

		annotation SummarizationSetBy = Automatic

	column StateName
		dataType: string
		lineageTag: f3c5b264-fba6-4944-99dd-e2fa61018935
		summarizeBy: none
		sourceColumn: StateName

		annotation SummarizationSetBy = Automatic

	column CountryCode
		dataType: string
		lineageTag: a7ee98a8-d693-4a16-9e3f-a309eacc22b7
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		lineageTag: b1ee8327-7e96-4631-a912-728357ffdf2c
		summarizeBy: none
		sourceColumn: CountryName

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 35f9b4aa-23be-418c-ab31-aca1d46a46eb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: 233b3ecb-e5fd-407c-bc71-b1bfda368ab0
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\elmnshawy\Desktop\DataX\Project one\Customers.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"GeographyKey", Int64.Type}, {"BusinessType", type text}, {"Customer", type text}, {"NumberEmployees", Int64.Type}, {"AnnualRevenue", Int64.Type}, {"YearOpened", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"GeographyKey"}, Geography, {"GeographyKey"}, "Geography", JoinKind.LeftOuter),
				    #"Expanded Geography" = Table.ExpandTableColumn(#"Merged Queries", "Geography", {"CityName", "StateCode", "StateName", "CountryCode", "CountryName", "Region", "Continent"}, {"CityName", "StateCode", "StateName", "CountryCode", "CountryName", "Region", "Continent"})
				in
				    #"Expanded Geography"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

