table SalesDetails
	lineageTag: 5dab06fb-87c5-4d5d-bc79-1b59d66da783

	column SalesDetailsKey
		dataType: int64
		formatString: 0
		lineageTag: 9927577f-7a5d-490a-bcce-2cfcccf1ea85
		summarizeBy: count
		sourceColumn: SalesDetailsKey

		annotation SummarizationSetBy = Automatic

	column SalesHeaderKey
		dataType: int64
		formatString: 0
		lineageTag: 97ccee03-2088-4a84-b7a3-07fb83e88fb5
		summarizeBy: count
		sourceColumn: SalesHeaderKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: fa23459c-2b51-4f07-90d6-0bf530e93666
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: a01809b2-c7f9-4657-93c2-a9b661255967
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: dbaa05cc-61a8-45e2-a0e5-458bea832a6f
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 1186e622-30e1-407a-bb3e-362811225034
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: da7ecb29-3822-48bb-bac5-84ca6838e85f
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		lineageTag: 6483b09f-6467-4810-bc37-592f1352c0fb
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		lineageTag: 21f0fd07-6fcf-4413-bb44-85a452d6b0f2
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales_amount
		dataType: double
		lineageTag: 4c170db2-8b03-40ba-ac0a-f24fe7fc9e64
		summarizeBy: sum
		sourceColumn: Sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesDetails
		dataType: int64
		formatString: 0
		lineageTag: 6139c168-dfc4-4ad7-a12b-b669bd27fada
		summarizeBy: sum
		sourceColumn: SalesDetails

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0e05989-5853-436b-b094-eeb28876857e
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d852c92c-7024-48f3-80e7-c79b922714bc
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: df37da30-46ba-4a4c-acfe-e6b190bab0ab
			defaultHierarchy: LocalDateTable_7e96eb74-b9a9-43e1-b2f9-c11399cfb732.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f8981279-ec56-4927-8a10-3b469aa04031
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 5e34be04-caa8-4139-9959-941569e30069
			defaultHierarchy: LocalDateTable_91aec3c3-1ce2-4d85-8af0-870a28da43a9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: f0d86463-fc38-42ef-9796-866dd4d176d0
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column CountryCode
		dataType: string
		lineageTag: 11255d1d-1053-48cb-b70f-641919f50a77
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 785df490-9662-4d77-a945-d3f539877c22
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 24fe4572-5583-4d22-a4b2-c81348494b27
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: 105e7c5a-8270-4439-a679-56daa5e852ea
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Category' = IF('SalesDetails'[UnitPrice]<1000,"0-1000",IF('SalesDetails'[UnitPrice]<=2000,"1000-2000",">2000"))
		lineageTag: d0f38592-d8d4-4295-a006-2adb587d2816
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition SalesDetails = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\DataX\Project one\SalesDetails.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Merged Queries" = Table.NestedJoin(#"Promoted Headers", {"SalesOrderNumber"}, SalesHeader, {"SalesOrderNumber"}, "SalesHeader", JoinKind.LeftOuter),
				    #"Expanded SalesHeader" = Table.ExpandTableColumn(#"Merged Queries", "SalesHeader", {"SalesDetails", "OrderDate", "DueDate", "ShipDate", "CustomerKey", "DiscountAmount", "TotalAmount", "SalesAmount"}, {"SalesDetails", "OrderDate", "DueDate", "ShipDate", "CustomerKey", "DiscountAmount", "TotalAmount", "SalesAmount"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded SalesHeader", {"CustomerKey"}, Customers, {"CustomerKey"}, "Customers", JoinKind.LeftOuter),
				    #"Expanded Customers" = Table.ExpandTableColumn(#"Merged Queries1", "Customers", {"CountryCode"}, {"CountryCode"}),
				    #"Inserted Year" = Table.AddColumn(#"Expanded Customers", "Year", each Date.Year([OrderDate]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([OrderDate]), Int64.Type),
				    #"Merged Queries2" = Table.NestedJoin(#"Inserted Month", {"ProductKey", "CountryCode", "Year", "Month"}, Productcosthistory, {"ProductKey", "CountryCode", "Year", "MonthNo"}, "Productcosthistory", JoinKind.LeftOuter),
				    #"Expanded Productcosthistory" = Table.ExpandTableColumn(#"Merged Queries2", "Productcosthistory", {"UnitCost"}, {"UnitCost"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded Productcosthistory", each true),
				    #"Inserted Division" = Table.AddColumn(#"Filtered Rows", "Division", each [ExtendedAmount] / [TotalAmount], type number),
				    #"Inserted Multiplication" = Table.AddColumn(#"Inserted Division", "Multiplication", each [Division] * [DiscountAmount], type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Multiplication",{"Division", "DiscountAmount", "TotalAmount", "SalesAmount"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Multiplication", "Discount"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"SalesDetailsKey", "SalesHeaderKey", "SalesOrderNumber", "ProductKey", "ProductSubcategoryKey", "OrderQuantity", "UnitPrice", "ExtendedAmount", "Discount", "SalesDetails", "OrderDate", "DueDate", "ShipDate", "CustomerKey", "CountryCode", "Year", "Month", "UnitCost"}),
				    #"Inserted Subtraction" = Table.AddColumn(#"Reordered Columns", "Subtraction", each [ExtendedAmount] - [Discount], type number),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Subtraction",{{"Subtraction", "Sales_amount"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"SalesDetailsKey", "SalesHeaderKey", "SalesOrderNumber", "ProductKey", "ProductSubcategoryKey", "OrderQuantity", "UnitPrice", "ExtendedAmount", "Discount", "Sales_amount", "SalesDetails", "OrderDate", "DueDate", "ShipDate", "CustomerKey", "CountryCode", "Year", "Month", "UnitCost"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns1",{{"OrderDate", type date}, {"SalesDetailsKey", Int64.Type}, {"SalesHeaderKey", Int64.Type}, {"SalesOrderNumber", type text}, {"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"OrderQuantity", Int64.Type}, {"UnitPrice", type number}, {"ExtendedAmount", type number}, {"Discount", type number}, {"Sales_amount", type number}, {"SalesDetails", Int64.Type}, {"DueDate", type date}, {"ShipDate", type date}, {"CustomerKey", Int64.Type}, {"CountryCode", type text}, {"Year", Int64.Type}, {"Month", Int64.Type}, {"UnitCost", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

